server:
  port: 8881

spring:
  http:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  flyway:
    out-of-order: true
    ignoreMissingMigrations: true

log:
  level: ERROR
  dir: ./log

#数据库相关
datasource:
  url: ENC(6YlH0q8czMrzruu017lnRmK8wVtP0ulIeJawOw2WILaw8x6bWHxM+3UG6QJJmzJUAhxmC7FDQApBjVxHrWvHdwOY26JwJqIXhkEuwxi2cuZ4OTRHiixBOALtjisoe5i4iJ23mYvdXozESZlgOBqY6/553QW+eL70kae61wkAZ2SgNz5kCmYM/Z2AEOD3IfzByjJV98wOiBiqDxpzlTCsZyHuVf1eV0IxIFx6X0KQzNeLCJEguOGBKw==)
  username: ENC(Xl9XRlx22kpxNqrhrPGzUg==)
  password: ENC(SqTjlJcCdNiNSqGHQRkFDQ==)
  driver-class-name: com.mysql.cj.jdbc.Driver
  maxActive: 100
  initialSize: 5
  maxWait: 60000
  minIdle: 5
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: "select 1"
  testWhileIdle: false
